# Generated by Django 3.1.1 on 2020-09-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinfo',
            name='media_id',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
